### PR TITLE
Fix FileSystem Provider crash issue

### PR DESCRIPTION
**Pull request by JumpingYang001**
@Microsoft/omi-devs , I fix this provider's issue, which can use for testing, please help to review it, thank you!

### CODE REVIEW

**Comment by JumpingYang001** [comment]
Fixed, thanks

**Comment by jeffaco** [comment]
Please rebase as well before submitting your next review, thanks.

**Comment by JumpingYang001** [comment]
Done, thanks

**Comment by JumpingYang001** [comment]
In fact, when we run `omicli a root/omi { MSFT_Directory Name "/opt" }` provider will not crash but omiserver crash...

**Comment by JumpingYang001** [comment]
Changed commit message to more read English, thanks.

**Comment by JumpingYang001** [comment]
Ho, will take care Capitalize next time, thanks.

**Pull request merged**
