### PR TITLE
Fixes double free issue

### PR DESCRIPTION
**Pull request by JumpingYang001**
@Microsoft/omi-devs @dantraMSFT  , fixed the double free issue #502 , could you help to review it? thanks.

### CODE REVIEW

**Comment by JumpingYang001** [comment]
@palladia you can check other place for "PAL_Free(operation->protocolConnection);" in interationprotocolhandler.c

pal_free will call systemfree which will call free which will not set it to null, Setting unused pointers to NULL is a defensive style, protecting against dangling pointer bugs.  previous logic operation->connection become unused pointer here, then when next checking in other place it is not null and can be free, then double free occurs.

next line operation also need to set to null, I will update it if no other issues, thanks.

**Comment by palladia** [comment]
I think you misunderstood me.  I do know what PAL_Free() does, and I do know why one sets the pointer to NULL after free.  I'm just not sure this will fix Dan's issue.  But let's wait for Dan's verification.

Anyway, if you want to be defensive, do something like:

if (operation)
{
    PAL_Free(operation->protocolConnection);
    operation->protocolConnection = NULL;
    PAL_Free(operation);
    operation = NULL;
}

**Comment by dantraMSFT** [comment]
I don't see how this can fix https://github.com/Microsoft/omi/issues/502 either.

The problem I saw was as follows:

InteractionProtocolHandler_Session_Connect calls WsmanClient_New_Connector with an allocated operation.  Before returning, the connection fails and the operation is freed.   This would be fine if WsmanClient_New_Connector returned a failing MI_RESULT  but it doesn't, it returns MI_RESULT_OK and the code assumes the operation is still a valid memory pointer.  As a result, the following line is executed:

if (operation->protocolConnection->protocol.wsman == NULL)

Since the operation has been freed, in debug builds, protocolConnection contains an invalid pointer value and we get a seg fault.  In release builds, we're accessing freed memory and it's state is indeterminate.

Even with the suggested changes, we'll get a seg fault because we'll be dereferencing a null pointer, protocolConnection.   If we add a protocolConnection null pointer check, we'll end up getting a random seg fault any time that memory block happens to get reused for something else.

The reliable fix needs to handle the case that operation itself has been freed.

**Comment by JumpingYang001** [comment]
thanks all! I got understand now. but after set to null, the double free Looks like disappear. anyway I will update the PR to make it sense.

**Comment by JumpingYang001** [comment]
@paulcallen @dantraMSFT , can you help to review the new changes? thank you!

**Comment by JumpingYang001** [comment]
@paulcallen @dantraMSFT , ping...

**Comment by JumpingYang001** [comment]
@paulcallen @dantraMSFT , ping...

**Comment by JumpingYang001** [comment]
@paulcallen , thanks for confirm! I'll debug the failed Pester test with double free issue to understand the underlying problem.

**Comment by JumpingYang001** [comment]
I don't have a good fix at present, so I want to close this PR, I will new a PR once I have a good fix, thanks.

**Pull request closed without merging**
