### PR TITLE
defunct: Adding features to OMI to support OMI-Script-Provider.

### PR DESCRIPTION
**Pull request by EMumau**

### CODE REVIEW

**Comment by paulcallen** [comment]
looks like you need to rebase, and you will need to squash your commit list into a single checking commit.

**Comment by paulcallen** [comment]
also, if they python stuff is not supported on any specific platform you may want to #ifdef the changes in the provider manager, and fail the registration on those platforms.

**Comment by JumpingYang001** [comment]
We should hold on this PR to wait non-root feature release then we can merge it and start Python Provider building and testing, thanks.

**Comment by JumpingYang001** [comment]
I will share here once non-root release then we can check it that time.
BTW, looks like omireg doesn't support c/c++ providers in your code:
```
root@py64-cent7-01  # /opt/omi/bin/omireg --hosting '@requestor@' -n root/cimv2 /root/Build-omi-script-provider/omi/Unix/output/lib/libScriptProvider.so
Created /opt/omi/lib/libScriptProvider.so
/opt/omi/bin/omireg: failed to find symbol 'MI_Main' in library '/root/Build-omi-script-provider/omi/Unix/output/lib/libScriptProvider.so'

```

**Pull request closed without merging**
