### PR TITLE
Check that system keytab exists in crontab

### PR DESCRIPTION
**Pull request by palladia**

### CODE REVIEW

**Comment by palladia** [comment]
microsoft/omi-devs

**Comment by JumpingYang001** [comment]
If systab exist, but ktutil doesn't install it will also get error in log.

**Comment by JumpingYang001** [comment]
in normal case, if systab exist ktutil should exist and work?

**Comment by yakman2020** [comment]
ktutil is a standard part of the system. Its like asking what happens in "ls" isn't installed.

**Pull request merged**
