### PR TITLE
ensure /bin/false is added in 'shells' value in login.cfg

### PR DESCRIPTION
**Pull request by BingyuLiu**
Fix "Error changing "shell" to "/bin/false" : Value is invalid."

### CODE REVIEW

**Comment by JumpingYang001** [comment]
Duplicated with #599 ?

**Comment by JumpingYang001** [comment]
#599 will also remove exist problem on customer's env, this PR doesn't consider this scenario, thanks.

**Comment by BingyuLiu** [comment]
yes, duplicated. I will give up my code change. :)

**Comment by BingyuLiu** [comment]
close it, since Jumping has fixed.

**Pull request closed without merging**
