### PR TITLE
With limitation: SDL items assigned to John

### PR DESCRIPTION
**Pull request by BingyuLiu**

### CODE REVIEW

**Comment by JumpingYang001** [comment]
duplicate with #603 ?

**Comment by BingyuLiu** [comment]
> duplicate with #603 ?

It is different, #603 has not a size limitation.

**Comment by BingyuLiu** [comment]
@JumpingYang001 , In some OS, the net.core.rmem_max  is 212992 by default. User can change it by modifying /etc/sysctl.conf file. I am not sure 50M is suitable, that is why I made 2 code changes 603 and 604.

**Comment by palladia** [comment]
Your new code doesn't even compile cleanly.  Please compile and test before submitting for review.

**Pull request closed without merging**
