### PR TITLE
Don't delete and re-create the user 'omi' if it is already exist

### PR DESCRIPTION
**Pull request by deepakjain111**

### CODE REVIEW

**Comment by sarojcare** [comment]
Is there any dependency on omi group? Do we need to make validation that omi user existing is also part of omi group?

**Comment by deepakjain111** [comment]
> Is there any dependency on omi group? Do we need to make validation that omi user existing is also part of omi group?

I don't think so. We don't need that validation.

**Comment by sarojcare** [comment]
Whether pbuild and unit testing has done? 

Also the comment line should not be longer than 70 chars. In case we need to have longer string please put it in a file with each line not having 70 chars and use it to commit.

**Comment by deepakjain111** [comment]
> Whether pbuild and unit testing has done?
> 
> Also the comment line should not be longer than 70 chars. In case we need to have longer string please put it in a file with each line not having 70 chars and use it to commit.

I have done unit testing and will ask testing team to test on all Linux system

**Pull request merged**
