### PR TITLE
Set omi:omi as omi.keytab's owner

### PR DESCRIPTION
**Pull request by BingyuLiu**

### CODE REVIEW

**Comment by JumpingYang001** [comment]
Negotiate file also need to chown : `[ -d /etc/opt/omi/.creds] && chown -R omi:omi /etc/opt/omi/.creds`
```
/etc/opt/omi/.creds/
/etc/opt/omi/.creds/ntlm
```

**Comment by JumpingYang001** [comment]
another file is `/etc/opt/omi/ssl/omikey.pem`, let me check today if it will be deleted after uninstallation.

**Comment by JumpingYang001** [comment]
I have confirmed that `/etc/opt/omi/ssl/omikey.pem` will exist after uninstallation on Negotiate environment.

**Comment by BingyuLiu** [comment]
@JumpingYang001 thanks, please review it again!

**Pull request merged**
